// 持久 fixture 的同段四来源为三个网页和一份知识文件，第二段使用同一知识文件。
// 已登录并打开真实会话后运行：playwright-cli run-code --filename=frontend/test/browser/sourceCapsules.js
// prettier-ignore
async (page) => {
  const check = (value, message) => { if (!value) throw new Error(message) }
  const card = page.getByRole('dialog', { name: '来源预览', exact: true })
  const capsules = page.locator('.reference-citation')
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.evaluate(() => localStorage.setItem('theme', 'light'))
  await page.reload()
  await capsules.first().waitFor()
  check(await capsules.count() === 2, '同段多个来源必须合并，不能堆叠四个胶囊')
  check(await capsules.first().textContent() === 'arxiv.org+3', '胶囊显示域名和额外来源数量')
  check(await page.locator('.reference-answer-active').count() === 0, '阅读正文时没有常驻底色')
  const filename = capsules.nth(1).locator('.reference-citation-label')
  check(await filename.evaluate(el => el.scrollWidth > el.clientWidth), '长文件名必须在胶囊中截断')
  await capsules.first().hover()
  await card.waitFor()
  check(await card.getByText('1/4', { exact: true }).isVisible(), '悬浮卡片显示来源序号')
  check(await page.locator('.reference-answer-active').count() === 1, '只强调当前查看的回答范围')
  await card.hover()
  await page.waitForTimeout(250)
  check(await card.isVisible(), '指针移到卡片时必须保持可读')
  await page.screenshot({ path: '/tmp/yuxi-source-capsules-light.png', fullPage: true })
  await page.mouse.move(0, 0)
  await capsules.first().focus()
  await page.keyboard.press('ArrowDown')
  check(await card.getByRole('button', { name: '下一个来源', exact: true }).evaluate(el => el === document.activeElement), '键盘可进入来源卡片')
  for (let index = 0; index < 3; index++) await page.keyboard.press('Enter')
  await page.waitForTimeout(250)
  check(await card.getByText('4/4', { exact: true }).isVisible(), '到末页后卡片和焦点不能消失')
  check(await card.getByRole('button', { name: '下一个来源', exact: true }).getAttribute('aria-disabled') === 'true', '末页必须显式标记不可再向后')
  check(await card.getByText('第 8–12 行', { exact: true }).isVisible(), '知识来源的权威行号保留')
  await card.getByRole('button', { name: '查看原文', exact: true }).click()
  const document = page.getByRole('dialog').filter({ has: page.getByRole('button', { name: '关闭预览', exact: true }) })
  await document.locator('.source-line-highlight').first().waitFor()
  check((await document.locator('.source-line-highlight').allTextContents()).join('').includes('知识库证据'), '切换到知识来源后必须打开正确原文')
  await document.getByRole('button', { name: '关闭预览', exact: true }).click()
  await capsules.first().focus()
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Escape')
  await card.waitFor({ state: 'detached' })
  check(await capsules.first().evaluate(el => el === document.activeElement), '关闭预览后焦点回到原胶囊')
  check(await page.locator('.reference-answer-active').count() === 0, '关闭后移除临时强调')
  await page.mouse.move(0, 0)
  await page.evaluate(() => document.activeElement.blur())
  await page.evaluate(() => localStorage.setItem('theme', 'dark'))
  await page.reload()
  await capsules.first().waitFor()
  await capsules.first().hover()
  await card.waitFor()
  check(await card.evaluate(el => getComputedStyle(el).backgroundColor === 'rgb(30, 31, 31)'), '深色卡片必须与正文背景区分')
  await page.screenshot({ path: '/tmp/yuxi-source-capsules-dark.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await capsules.first().click()
  await card.waitFor()
  check(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), '手机宽度没有横向溢出')
  await page.screenshot({ path: '/tmp/yuxi-source-capsules-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 320, height: 200 })
  await capsules.first().focus()
  // 胶囊聚焦会滚动原文；等滚动完成后再验证卡片自己的滚动。
  await page.waitForTimeout(400)
  await page.keyboard.press('ArrowDown')
  await card.waitFor()
  const rect = await card.boundingBox()
  check(rect.x >= 12 && rect.x + rect.width <= 308 && rect.y >= 12 && rect.y + rect.height <= 188, '卡片必须在低高度小窗口内')
  await card.evaluate(el => { el.scrollTop = el.scrollHeight })
  await page.waitForTimeout(250)
  check(await card.isVisible(), '卡片内部滚动不能关闭预览')
  const open = await card.getByRole('button', { name: '打开网页', exact: true }).boundingBox()
  check(open.y >= 12 && open.y + open.height <= 188, '内部滚动后打开按钮必须可达')
  await page.keyboard.press('Escape')
  await page.setViewportSize({ width: 1440, height: 1000 })
  return { capsules: 2, groupedSources: 4, keyboardPagination: true, documentLines: '8–12', shortViewport: true, themes: ['light', 'dark'] }
}
