// 已登录并打开真实检索 fixture 会话后运行：playwright-cli run-code --filename=frontend/test/browser/turnReferences.js
// prettier-ignore
async (page) => {
  const check = (value, message) => { if (!value) throw new Error(message) }
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.evaluate(() => localStorage.setItem('theme', 'light'))
  await page.reload()
  const mark = page.getByRole('button', { name: '标注来源', exact: true }).first()
  await mark.waitFor()
  let release
  const referenceRequests = []
  page.on('request', request => {
    const url = new URL(request.url())
    if (url.pathname.endsWith('/references')) referenceRequests.push(url.pathname)
  })
  const gate = new Promise(resolve => { release = resolve })
  await page.route('**/references', async route => {
    if (route.request().method() === 'POST') await gate
    await route.continue()
  })
  await mark.click()
  const loading = page.getByRole('button', { name: '正在标注…', exact: true }).first()
  await loading.waitFor()
  check(await loading.isDisabled(), '在途标注按钮必须禁用')
  await page.screenshot({ path: '/tmp/yuxi-turn-refs-loading.png', fullPage: true })
  release()
  await page.getByRole('button', { name: '隐藏标注', exact: true }).first().waitFor()
  await page.unroute('**/references')
  const badges = page.locator('.reference-citation')
  check(await badges.count() === 2, '两条已持久化证据必须各有一个角标')
  check(await badges.nth(0).textContent() === '测试报告.md', '胶囊直接显示文件名')
  check(await badges.nth(1).textContent() === 'example.org', '网页胶囊直接显示域名')
  await badges.nth(0).hover()
  const preview = page.getByRole('dialog', { name: '来源预览', exact: true })
  await preview.waitFor()
  check(await preview.getByText('第 8–12 行', { exact: true }).isVisible(), '来源卡片必须含真实行号')
  check(await preview.getByText('知识库证据', { exact: true }).isVisible(), '来源卡片必须展示证据')
  check(await page.locator('.reference-answer-highlight').count() === 2, '只高亮对应的两段回答')
  check(await page.locator('h1.reference-answer-highlight').count() === 0, '无引用标题不能被染色')
  await page.screenshot({ path: '/tmp/yuxi-turn-refs-light.png', fullPage: true })
  await badges.nth(0).focus()
  await page.keyboard.press('Enter')
  const modal = page.getByRole('dialog')
  await modal.waitFor()
  await modal.locator('.source-line-highlight').first().waitFor()
  check((await modal.locator('.source-line-highlight').allTextContents()).join('').includes('知识库证据'), '弹窗必须定位到原文证据')
  await modal.getByTitle('Markdown 源码', { exact: true }).click()
  await modal.locator('.source-row.highlighted').first().waitFor()
  check(await modal.locator('.source-row.highlighted').count() === 5, '源码视图只高亮第 8–12 行')
  check(await modal.locator('.source-row.highlighted').first().getAttribute('data-line') === '8', '起始行必须是 8')
  await page.waitForTimeout(200)
  await page.screenshot({ path: '/tmp/yuxi-turn-refs-document.png', fullPage: true })
  await modal.getByRole('button', { name: '关闭预览', exact: true }).click()
  const popupPromise = page.waitForEvent('popup')
  await badges.nth(1).click()
  const popup = await popupPromise
  await popup.waitForURL('https://example.org/reference')
  await popup.close()
  await page.getByRole('button', { name: '隐藏标注', exact: true }).first().click()
  await badges.first().waitFor({ state: 'detached' })
  check(await badges.count() === 0, '隐藏标注必须移除角标与高亮')
  await page.getByRole('button', { name: '显示标注', exact: true }).first().click()
  await page.reload()
  await page.locator('.reference-citation').first().waitFor()
  check(await page.locator('.reference-citation').count() === 2, '刷新必须恢复持久结果')
  check(referenceRequests.length >= 2 && referenceRequests.every(path => /^\/api\/agent\/threads\/[^/]+\/turns\/[^/]+\/references$/.test(path)), '标注与恢复必须只调用 Web 内部接口')
  await page.evaluate(() => localStorage.setItem('theme', 'dark'))
  await page.reload()
  await page.locator('.reference-citation').first().waitFor()
  check(await page.evaluate(() => document.documentElement.classList.contains('dark')), '暗色主题必须由真实应用初始化')
  await page.screenshot({ path: '/tmp/yuxi-turn-refs-dark.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  check(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), '窄屏不能横向溢出')
  await page.screenshot({ path: '/tmp/yuxi-turn-refs-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  return { citations: 2, documentLocation: '8–12', refreshed: true, internalReferences: true, themes: ['light', 'dark'], mobile: true }
}
